### ISSUE TITLE
Remove AppMode

### ISSUE THREAD

**Issue by ocefpaf** [reproducible-notebooks/ERDDAP_timeseries_explorer#13]
We'll use Panel so no need for two binder links.

PS: @apkrelling can you do that?

**Comment by apkrelling** [comment]
@ocefpaf this should be fixed by the commit in PR #18 . However, just like PR #17, it has not passed the pre-commit test.

**Comment by ocefpaf** [comment]
> @ocefpaf this should be fixed by the commit in PR #18 . However, just like PR #17, it has not passed the pre-commit test.

Don't worry about them at the moment. We need to remove the .py file, if @rsignell-usgs agree to use notebooks diffs only, and then we can fix the notebook.
