### ISSUE TITLE
First step towards a refactor

### ISSUE THREAD

**Issue by ocefpaf** [reproducible-notebooks/ERDDAP_timeseries_explorer#14]
We need to split the code that fetches the data and the that creates that app. Before we do that let's clean the code up a little.

- [x] remove duplication and aggregate the multiple servers in a dict that can be used later in the app
- [x] remove left-over commented code
- [x] check with flake8
- [x] blacken the code

**Comment by apkrelling** [comment]
PR #19 should complete the first task.

**Comment by apkrelling** [comment]
I added some things on PR #19  to improve readability.

**Comment by apkrelling** [comment]
PR #20 should solve the third and fourth tasks.

**Comment by ocefpaf** [comment]
We need to re-issue #19, close this one, and move to the next step!

**Comment by apkrelling** [comment]
I'll close #19 without merging to master, since its purpose was accomplished by #22. Also, I'll get a new PR to complete the second task of this issue (remove left-over commented code).

**Comment by apkrelling** [comment]
PR #23 completes the removal of left-over commented code.
