### ISSUE TITLE
Fix flawed logic for standard_name list

### ISSUE THREAD

**Issue by rsignell-usgs** [reproducible-notebooks/ERDDAP_timeseries_explorer#6]
As reported by @BobSimons, 

> For me (Chrome on Win 7), "water_level" makes the page shrink into a smaller area with a scroll bar.
> And some standard_names don't work, e.g., sea_water_temperature_data_quality.

This is because my logic was flawed.  

I'm finding all the `standard_name`s that exist on erddap using categorize and putting them on the list.

But that doesn't mean that a particular `standard_name` will be found within the time period specified. 

I need to filter the `standard_name` list by the time period selected.

And eventually hook up time widgets that would change the `standard_name` dropdown menu interactively.

**Comment by apkrelling** [comment]
This has been fixed on PR #27 .
